"""STEP 5: Guidance generator — Korean guidance text per DP.

Generates Guidance (primary + pre_alert + action) per DP using a
conversational tone. Distance-in-meters phrasing is avoided in fallbacks
("곧" / "조금만 더 가면" instead of "50m 앞").

VIRTUAL DPs are normally generated by midpoint_service; the VIRTUAL
template here is kept for unit tests and edge-case callers.
"""

from __future__ import annotations

from dataclasses import dataclass

from constants import (
    FACILITY_KOREAN_NAMES,
    FACILITY_TURN_TYPES,
    TURN_TYPE_TO_ACTION,
)
from schemas import DecisionPoint, Guidance
from scoring_service import ScoredPoi

# ---------------------------------------------------------------------------
# Position text mapping
# ---------------------------------------------------------------------------

POSITION_TEXT: dict[str, str] = {
    "LEFT": "왼쪽에",
    "RIGHT": "오른쪽에",
    "FRONT": "전방에",
}

# ---------------------------------------------------------------------------
# Action text mapping (GuidanceAction → Korean)
# ---------------------------------------------------------------------------

ACTION_TEXT: dict[str, str] = {
    "LEFT_TURN": "좌회전",
    "RIGHT_TURN": "우회전",
    "U_TURN": "유턴",
    "CROSSWALK": "횡단보도",
    "STAIRS_UP": "올라가세요",
    "STAIRS_DOWN": "내려가세요",
    "OVERPASS": "건너세요",
    "UNDERPASS": "내려가세요",
    "ELEVATOR": "이용하세요",
}

# Direction-only text for pre_alert / no-landmark fallbacks
DIRECTION_TEXT: dict[str, str] = {
    "LEFT_TURN": "왼쪽",
    "RIGHT_TURN": "오른쪽",
    "U_TURN": "뒤쪽",
}

# ---------------------------------------------------------------------------
# Facility text (turnType → action verb only, no facility prefix)
# ---------------------------------------------------------------------------

# Action verb only — facility name is prepended dynamically in templates.
FACILITY_ACTION_VERB: dict[int, str] = {
    125: "건너세요",
    126: "내려가세요",
    127: "올라가세요",
    128: "내려가세요",
    129: "올라가세요",
    218: "이용하세요",
}

# ---------------------------------------------------------------------------
# Korean particle helper (조사 처리)
# ---------------------------------------------------------------------------


def _has_batchim(char: str) -> bool:
    """Check if a Korean character has a final consonant (받침).

    Args:
        char: single character to check.

    Returns:
        True if the character has batchim, False otherwise.
        Non-Korean characters are treated as no batchim.
    """
    if not ("가" <= char <= "힣"):
        return False
    return (ord(char) - 0xAC00) % 28 != 0


def _particle(name: str, with_batchim: str, without_batchim: str) -> str:
    """Append the correct Korean particle to a name.

    Args:
        name: the noun to attach the particle to.
        with_batchim: particle form when last char has batchim.
        without_batchim: particle form when last char has no batchim.

    Returns:
        name + appropriate particle.
    """
    if not name:
        return name
    last_char = name.rstrip()[-1]
    particle = with_batchim if _has_batchim(last_char) else without_batchim
    return f"{name}{particle}"


# ---------------------------------------------------------------------------
# GuidanceInput dataclass
# ---------------------------------------------------------------------------


@dataclass
class GuidanceInput:
    """All context needed to generate guidance for a single DP."""

    dp_index: int
    dp_type: str
    turn_type: int | None
    action: str | None
    distance_from_start: float
    selected_landmark: ScoredPoi | None
    match_status: str | None
    environment_desc: str | None
    facility_visible: bool | None
    prev_landmark_name: str | None
    next_dp_distance: float | None


# ---------------------------------------------------------------------------
# Internal text builders
# ---------------------------------------------------------------------------


def _get_action_text(action: str | None) -> str:
    """Convert GuidanceAction to Korean verb form.

    Args:
        action: GuidanceAction enum value.

    Returns:
        Korean action text, defaults to "직진".
    """
    if action is None:
        return "직진"
    return ACTION_TEXT.get(action, "직진")


def _landmark_with_env(
    landmark: ScoredPoi | None,
    match_status: str | None,
    environment_desc: str | None,
    distance_from_start: float = 0.0,
    next_dp_distance: float | None = None,
) -> str:
    """Build landmark reference text based on match_status.

    Args:
        landmark: selected landmark (may be None).
        match_status: POI_ONLY in production; MATCHED/VISION_ONLY are reserved for future Vision integration.
        environment_desc: Optional environment description reserved for future Vision integration.
        distance_from_start: for distance fallback.
        next_dp_distance: distance to next DP (for fallback text).

    Returns:
        Landmark reference string for embedding in guidance templates.
    """
    if landmark is None or match_status is None:
        if next_dp_distance is not None:
            return f"{int(next_dp_distance)}m 앞"
        return f"{int(distance_from_start)}m 앞"

    name = landmark.poi.place_name

    if match_status == "MATCHED":
        return name
    elif match_status == "POI_ONLY":
        if environment_desc:
            return f"{environment_desc} {name}"
        return name
    elif match_status == "VISION_ONLY":
        if environment_desc:
            return environment_desc
        return name
    return name


def _name_with_optional_appearance(name: str, environment_desc: str | None) -> str:
    if environment_desc:
        return f"{environment_desc} {name}"
    return name


def _position_text(landmark: ScoredPoi | None) -> str:
    """Get position text for a landmark.

    Args:
        landmark: selected landmark.

    Returns:
        Korean position text (e.g., "왼쪽에").
    """
    if landmark is None:
        return "전방에"
    return POSITION_TEXT.get(landmark.poi.position, "전방에")


# ---------------------------------------------------------------------------
# Per-type guidance generators
# ---------------------------------------------------------------------------


def _generate_departure(
    turn_type: int | None,
    action: str | None,
    **kwargs,
) -> Guidance:
    """Generate DEPARTURE guidance.

    Args:
        turn_type: Tmap turnType.
        action: next DP's action (not this DP's).

    Returns:
        Guidance with fixed departure text.
    """
    primary = "안내를 시작합니다. 직진하세요."
    return Guidance(primary=primary, pre_alert=None, action=None)


def _generate_arrival(
    dest_name: str = "",
    **kwargs,
) -> Guidance:
    """Generate ARRIVAL guidance.

    Args:
        dest_name: destination name.

    Returns:
        Guidance with arrival text.
    """
    if dest_name:
        primary = f"목적지 {dest_name}에 도착했습니다!"
    else:
        primary = "목적지에 도착했습니다!"
    return Guidance(primary=primary, pre_alert=None, action=None)


def _generate_direction_change(
    turn_type: int | None,
    action: str | None,
    landmark: ScoredPoi | None,
    match_status: str | None,
    environment_desc: str | None,
    prev_landmark_name: str | None,
    distance_from_start: float,
    next_dp_distance: float | None,
    tmap_description: str | None = None,
) -> Guidance:
    """Generate DIRECTION_CHANGE guidance (PRE_ALERT + PRIMARY pair).

    Notion templates:
      With landmark:
        pre_alert: "곧 {direction}에 {name}이/가 보일 거예요."
        primary:   "{name}을/를 끼고 {action}하세요."
      Without landmark:
        pre_alert: "곧 {direction}으로 꺾이는 길이 나와요."
        primary:   "{direction}으로 꺾으세요."

    With prev_landmark_name (chain variant):
        pre_alert: "{prev_name} 지나서 조금만 더 가면 {name}이/가 보일 거예요."
    """
    action_text = _get_action_text(action)
    direction = DIRECTION_TEXT.get(action or "", "앞")

    has_landmark = landmark is not None and match_status is not None

    # primary
    if has_landmark:
        name = _name_with_optional_appearance(
            landmark.poi.place_name,
            environment_desc,
        )
        name_with_particle = _particle(name, "을", "를")
        primary = f"{name_with_particle} 끼고 {action_text}하세요."
    else:
        # No landmark — direction-based phrasing, no meters.
        direction_with_ro = _particle(direction, "으로", "로")
        primary = f"{direction_with_ro} 꺾으세요."

    # pre_alert
    if has_landmark:
        name = _name_with_optional_appearance(
            landmark.poi.place_name,
            environment_desc,
        )
        name_with_particle = _particle(name, "이", "가")
        if prev_landmark_name:
            pre_alert = (
                f"{prev_landmark_name} 지나서 조금만 더 가면 "
                f"{name_with_particle} 보일 거예요."
            )
        else:
            pre_alert = f"곧 {direction}에 {name_with_particle} 보일 거예요."
    else:
        direction_with_ro = _particle(direction, "으로", "로")
        pre_alert = f"곧 {direction_with_ro} 꺾이는 길이 나와요."

    return Guidance(primary=primary, pre_alert=pre_alert, action=action)


def _generate_crosswalk(
    turn_type: int | None,
    action: str | None,
    landmark: ScoredPoi | None,
    match_status: str | None,
    environment_desc: str | None,
    facility_visible: bool | None,
    distance_from_start: float,
    next_dp_distance: float | None,
    after_landmark: ScoredPoi | None = None,
    after_match_status: str | None = None,
    after_environment_desc: str | None = None,
    tmap_description: str | None = None,
) -> Guidance:
    """Generate CROSSWALK guidance (before + after crossing).

    Notion templates:
      Both landmarks present:
        pre_alert: "곧 {before} 앞의 횡단보도를 건널 거예요."
        primary:   "{before} 앞의 횡단보도를 건너서, {after} 방향으로 가세요."
      Only before:
        pre_alert: "곧 {before} 앞의 횡단보도를 건널 거예요."
        primary:   "{before} 앞의 횡단보도를 건너서 직진하세요."
      Only after:
        pre_alert: "곧 횡단보도가 나와요. 건널 준비를 하세요."
        primary:   "횡단보도를 건너서 {after} 방향으로 가세요."
      Neither (incl. facility_visible=False):
        pre_alert: "곧 횡단보도가 나와요. 건널 준비를 하세요."
        primary:   "횡단보도를 건너서 직진하세요."
    """
    has_before = (
        landmark is not None
        and match_status is not None
        and facility_visible is not False
    )
    has_after = after_landmark is not None and after_match_status is not None

    before_name = (
        _name_with_optional_appearance(landmark.poi.place_name, environment_desc)
        if has_before
        else None
    )
    after_name = (
        _name_with_optional_appearance(after_landmark.poi.place_name, after_environment_desc)
        if has_after
        else None
    )

    # pre_alert
    if before_name:
        pre_alert = f"곧 {before_name} 앞의 횡단보도를 건널 거예요."
    else:
        pre_alert = "곧 횡단보도가 나와요. 건널 준비를 하세요."

    # primary
    if before_name and after_name:
        primary = (
            f"{before_name} 앞의 횡단보도를 건너서, "
            f"{after_name} 방향으로 가세요."
        )
    elif before_name:
        primary = f"{before_name} 앞의 횡단보도를 건너서 직진하세요."
    elif after_name:
        primary = f"횡단보도를 건너서 {after_name} 방향으로 가세요."
    else:
        primary = "횡단보도를 건너서 직진하세요."

    return Guidance(primary=primary, pre_alert=pre_alert, action=action)


def _generate_vertical_move(
    turn_type: int | None,
    action: str | None,
    landmark: ScoredPoi | None,
    match_status: str | None,
    environment_desc: str | None,
    facility_visible: bool | None,
    distance_from_start: float,
    next_dp_distance: float | None,
) -> Guidance:
    """Generate VERTICAL_MOVE guidance (fixed facility + POI assist).

    Notion templates:
      With landmark:
        primary: "{name}을/를 지나 바로 {facility}이/가 있어요. {action_verb}."
      Without landmark (incl. facility_visible=False):
        primary: "{facility}이/가 나와요. {action_verb}."
    """
    facility_type = FACILITY_TURN_TYPES.get(turn_type or 0, "")
    facility_korean = FACILITY_KOREAN_NAMES.get(facility_type, "시설물")
    action_verb = FACILITY_ACTION_VERB.get(turn_type or 0, "이용하세요")

    facility_with_particle = _particle(facility_korean, "이", "가")

    has_landmark = (
        landmark is not None
        and match_status is not None
        and facility_visible is not False
    )

    if has_landmark:
        name = _name_with_optional_appearance(
            landmark.poi.place_name,
            environment_desc,
        )
        name_with_particle = _particle(name, "을", "를")
        primary = (
            f"{name_with_particle} 지나 바로 "
            f"{facility_with_particle} 있어요. {action_verb}."
        )
    else:
        primary = f"{facility_with_particle} 나와요. {action_verb}."

    return Guidance(primary=primary, pre_alert=None, action=action)


def _generate_virtual(
    landmark: ScoredPoi | None,
    match_status: str | None,
    environment_desc: str | None,
    distance_from_start: float,
    next_dp_distance: float | None,
) -> Guidance:
    """Generate VIRTUAL (midpoint confirmation) guidance.

    Args:
        landmark: selected landmark.
        match_status: cross-validation result.
        environment_desc: Optional environment description reserved for future Vision integration.
        distance_from_start: distance from route start.
        next_dp_distance: distance to next DP.

    Returns:
        Guidance with confirmation text.
    """
    if landmark is None or match_status is None:
        return Guidance(
            primary="직진하세요. 잘 가고 있어요.",
            pre_alert=None,
            action=None,
        )

    pos_text = _position_text(landmark)
    lm_text = _landmark_with_env(
        landmark, match_status, environment_desc,
        distance_from_start, next_dp_distance,
    )
    lm_with_particle = _particle(lm_text, "이", "가")

    primary = (
        f"{pos_text} {lm_with_particle} 보이면 잘 가고 있는 거예요. "
        f"계속 직진하세요."
    )
    return Guidance(primary=primary, pre_alert=None, action=None)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_guidance(
    dp_type: str,
    turn_type: int | None,
    selected_landmark: ScoredPoi | None,
    match_status: str | None,
    environment_desc: str | None,
    facility_visible: bool | None,
    prev_landmark_name: str | None,
    next_dp_distance: float | None,
    dest_name: str = "",
    distance_from_start: float = 0.0,
    next_action: str | None = None,
    after_landmark: ScoredPoi | None = None,
    after_match_status: str | None = None,
    after_environment_desc: str | None = None,
    tmap_description: str | None = None,
) -> Guidance:
    """Generate guidance text for a single DP.

    Args:
        dp_type: DP type enum value.
        turn_type: Tmap turnType code (None for VIRTUAL).
        selected_landmark: Best landmark from sequence optimizer.
        match_status: Cross-validation result.
        environment_desc: Optional environment description reserved for future Vision integration.
        facility_visible: Optional future Vision visibility flag; production passes None.
        prev_landmark_name: Previous DP's landmark name.
        next_dp_distance: Distance to next DP in meters.
        dest_name: Destination name (for ARRIVAL).
        distance_from_start: Distance from route start.
        next_action: Next DP's action (for DEPARTURE).
        after_landmark: After-crossing landmark (for CROSSWALK).
        after_match_status: After-crossing match_status (for CROSSWALK).
        after_environment_desc: After-crossing env desc (for CROSSWALK).
        tmap_description: Original Tmap description (fallback for no-POI DPs).

    Returns:
        Guidance with primary, pre_alert, and action fields.
    """
    action = TURN_TYPE_TO_ACTION.get(turn_type, None) if turn_type else None

    if dp_type == "DEPARTURE":
        return _generate_departure(turn_type, next_action)

    if dp_type == "ARRIVAL":
        return _generate_arrival(dest_name)

    if dp_type == "DIRECTION_CHANGE":
        return _generate_direction_change(
            turn_type, action, selected_landmark, match_status,
            environment_desc, prev_landmark_name,
            distance_from_start, next_dp_distance,
            tmap_description=tmap_description,
        )

    if dp_type == "CROSSWALK":
        return _generate_crosswalk(
            turn_type, action, selected_landmark, match_status,
            environment_desc, facility_visible,
            distance_from_start, next_dp_distance,
            after_landmark, after_match_status, after_environment_desc,
            tmap_description=tmap_description,
        )

    if dp_type == "VERTICAL_MOVE":
        return _generate_vertical_move(
            turn_type, action, selected_landmark, match_status,
            environment_desc, facility_visible,
            distance_from_start, next_dp_distance,
        )

    if dp_type == "VIRTUAL":
        return _generate_virtual(
            selected_landmark, match_status,
            environment_desc, distance_from_start, next_dp_distance,
        )

    # Unknown dp_type fallback
    return Guidance(primary="직진하세요.", pre_alert=None, action=None)


def generate_all_guidance(
    decision_points: list[DecisionPoint],
    selected_landmarks: list[ScoredPoi | None],
    match_statuses: list[str | None],
    environment_descs: list[str | None],
    facility_visibles: list[bool | None],
    dest_name: str = "",
    after_landmarks: list[ScoredPoi | None] | None = None,
    after_match_statuses: list[str | None] | None = None,
    after_environment_descs: list[str | None] | None = None,
) -> list[Guidance]:
    """Generate guidance for all DPs in sequence.

    Handles prev_landmark_name chaining and next_action/next_dp_distance
    derivation automatically.

    Args:
        decision_points: ordered list of DecisionPoints.
        selected_landmarks: one per DP (None if no landmark).
        match_statuses: one per DP.
        environment_descs: one per DP.
        facility_visibles: one per DP.
        dest_name: destination name (for ARRIVAL DP).
        after_landmarks: crosswalk after-crossing landmarks (one per DP, None for non-crosswalk).
        after_match_statuses: crosswalk after-crossing match_statuses.
        after_environment_descs: crosswalk after-crossing environment descriptions.

    Returns:
        List of Guidance, one per DP.
    """
    n = len(decision_points)
    _after_landmarks = after_landmarks or [None] * n
    _after_match_statuses = after_match_statuses or [None] * n
    _after_environment_descs = after_environment_descs or [None] * n

    results: list[Guidance] = []
    prev_landmark_name: str | None = None

    for i, dp in enumerate(decision_points):
        # Compute next_dp_distance
        if i < n - 1:
            next_dp = decision_points[i + 1]
            next_dp_distance = next_dp.distance_from_start - dp.distance_from_start
        else:
            next_dp_distance = None

        # Compute next_action for DEPARTURE
        next_action: str | None = None
        if dp.dp_type == "DEPARTURE" and i < n - 1:
            next_tt = decision_points[i + 1].turn_type
            if next_tt is not None:
                next_action = TURN_TYPE_TO_ACTION.get(next_tt)

        guidance = generate_guidance(
            dp_type=dp.dp_type,
            turn_type=dp.turn_type,
            selected_landmark=selected_landmarks[i],
            match_status=match_statuses[i],
            environment_desc=environment_descs[i],
            facility_visible=facility_visibles[i],
            prev_landmark_name=prev_landmark_name,
            next_dp_distance=next_dp_distance,
            dest_name=dest_name,
            distance_from_start=dp.distance_from_start,
            next_action=next_action,
            after_landmark=_after_landmarks[i],
            after_match_status=_after_match_statuses[i],
            after_environment_desc=_after_environment_descs[i],
        )

        results.append(guidance)

        # Update prev_landmark_name for next DP
        if selected_landmarks[i] is not None:
            prev_landmark_name = selected_landmarks[i].poi.place_name
        else:
            prev_landmark_name = None

    return results
