server:
  port: 8080

spring:
   profiles:
     active: mock   # Python 서버 없이 테스트할 때 주석 해제

services:
  python:
    base-url: ${PYTHON_SERVICE_URL:http://localhost:8000}
  deviation:
    base-url: ${PYTHON_SERVICE_URL:http://localhost:8000}
